from actions.cleaning.handle_missing import HandleMissingAction
from actions.cleaning.handle_duplicates import HandleDuplicatesAction
from actions.cleaning.handle_outliers import HandleOutliersAction
from actions.cleaning.text_cleaning import TextCleaningAction
from actions.cleaning.inconsistency import InconsistencyAction